server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 2KB
    mime-types: video/mpeg4-generic, video/mpeg, video/mp4, video/ogg, video/3gpp, video/x-matroska, video/flv
    ffmpeg: ${FFMPEG_PATH:ffmpeg}
    ffprobe: ${FFPROBE_PATH:ffprobe}
spring:
  application:
    name: uploader
  datasource:
    url: jdbc:mariadb://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:video_streaming}
    username: ${MYSQL_USERNAME:upload}
    password: ${MYSQL_PASSWORD:upload}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database: mysql
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  servlet:
    multipart:
      enabled: true
      max-request-size: 200MB
      max-file-size: 200MB
  mvc:
    dispatch-options-request: true
org.jobrunr:
  job-scheduler:
    enabled: true
  background-job-server:
    enabled: true
  dashboard:
    enabled: true